import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
export default function SettingsPage() {
    const [leftColor, setLeftColor] = useState('#7067E8');
    const [rightColor, setRightColor] = useState('#ED5B4D');
    const ledColors = ['#ED5B4D', '#FF9F43', '#FFD166', '#55C89F', '#48A9E6', '#7067E8', '#B865D6', '#F4F1EB'];
    return (_jsxs("section", { className: "app-content min-w-0 space-y-5 lg:p-6 xl:p-8", children: [_jsx("div", { className: "rounded-[20px] border border-[#e5e7ec] bg-white p-5 shadow-[0_8px_28px_rgba(23,32,51,0.03)] sm:p-7", children: _jsxs("div", { className: "flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between", children: [_jsxs("div", { children: [_jsx("span", { className: "text-[10px] font-bold uppercase tracking-[0.08em] text-[#8c93a1]", children: "Connected device" }), _jsx("h2", { className: "mt-2 text-xl font-bold tracking-[-0.03em]", children: "Keylight One" }), _jsx("p", { className: "mt-1 text-xs text-[#8d94a2]", children: "Your color changes are applied to the keyboard instantly." })] }), _jsxs("span", { className: "inline-flex w-fit items-center gap-2 rounded-full bg-[#edf8f3] px-3 py-1.5 text-[10px] font-bold text-[#42966f]", children: [_jsx("i", { className: "h-2 w-2 rounded-full bg-[#4fbd8b]" }), "Connected"] })] }) }), _jsxs("div", { className: "rounded-[20px] border border-[#e5e7ec] bg-white p-5 shadow-[0_8px_28px_rgba(23,32,51,0.03)] sm:p-7", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-lg font-bold", children: "LED hand colors" }), _jsx("p", { className: "mt-1.5 text-xs leading-5 text-[#8d94a2]", children: "Choose a distinct guide color for each hand." })] }), _jsx("span", { className: "rounded-full bg-[#edf8f3] px-2 py-1 text-[9px] font-bold uppercase tracking-wide text-[#459a73]", children: "Live" })] }), _jsx("div", { className: "mt-7 grid gap-7 sm:grid-cols-2", children: [
                            { label: 'Left hand', value: leftColor, setter: setLeftColor },
                            { label: 'Right hand', value: rightColor, setter: setRightColor },
                        ].map((hand) => (_jsxs("div", { className: "rounded-2xl border border-[#e8eaee] bg-[#fafbfc] p-4", children: [_jsxs("div", { className: "mb-4 flex items-center justify-between", children: [_jsx("span", { className: "text-sm font-semibold", children: hand.label }), _jsxs("span", { className: "flex items-center gap-2 text-[10px] font-medium uppercase text-[#9197a4]", children: [_jsx("i", { className: "h-2.5 w-2.5 rounded-full", style: {
                                                        backgroundColor: hand.value,
                                                        boxShadow: `0 0 6px ${hand.value}`,
                                                    } }), hand.value] })] }), _jsx("div", { className: "flex flex-wrap gap-3", children: ledColors.map((color) => (_jsx("button", { onClick: () => hand.setter(color), className: `flex h-8 w-8 items-center justify-center rounded-full transition hover:scale-110 ${hand.value === color ? 'ring-2 ring-[#303649] ring-offset-2' : ''}`, style: { backgroundColor: color }, "aria-label": `Set ${hand.label} to ${color}`, children: hand.value === color && (_jsx("span", { className: `h-1.5 w-1.5 rounded-full ${color === '#F4F1EB' ? 'bg-[#555]' : 'bg-white'}` })) }, color))) }), _jsx("div", { className: "mt-4 border-t border-[#e8eaee] pt-4", children: _jsxs("label", { className: "flex cursor-pointer items-center justify-between", children: [_jsxs("span", { children: [_jsx("span", { className: "block text-xs font-semibold text-[#4d5566]", children: "Custom color" }), _jsx("span", { className: "mt-0.5 block text-[10px] text-[#969ca8]", children: "Choose any LED color" })] }), _jsx("span", { className: "relative flex h-9 w-12 items-center justify-center overflow-hidden rounded-lg border border-[#dfe2e7] bg-white shadow-sm", children: _jsx("input", { type: "color", value: hand.value, onChange: (e) => hand.setter(e.target.value.toUpperCase()), className: "absolute h-14 w-16 cursor-pointer border-0 bg-transparent p-0", "aria-label": `Choose custom color for ${hand.label}` }) })] }) })] }, hand.label))) })] })] }));
}
