import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import Icon from './Icon';
import Cover from './Cover';
import { formatTime } from '../utils/format';
export default function PlayerCard({ status, song, onPlay, onPause, onSeek, onSkip, }) {
    const [volume, setVolume] = useState(72);
    if (!status || !song) {
        return (_jsx("div", { className: "rounded-[20px] border border-[#e5e7ec] bg-white p-5 shadow-[0_8px_28px_rgba(23,32,51,0.04)] sm:p-7", children: _jsx("p", { className: "text-center text-sm text-[#8a91a0]", children: "No song selected" }) }));
    }
    const progress = Math.min(100, (status.elapsed / (status.duration || 1)) * 100);
    return (_jsx("div", { className: "rounded-[20px] border border-[#e5e7ec] bg-white p-5 shadow-[0_8px_28px_rgba(23,32,51,0.04)] sm:p-7", children: _jsxs("div", { className: "flex flex-col gap-5 sm:flex-row sm:items-center", children: [_jsx(Cover, { accent: song.metadata?.accent || '#d9d6ea', mark: song.metadata?.mark || '#5d518c', large: true }), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsxs("div", { className: "flex items-start justify-between gap-3", children: [_jsxs("div", { children: [_jsx("span", { className: "rounded-full bg-[#f0eefc] px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.08em] text-[#6559d9]", children: "Now learning" }), _jsx("h2", { className: "mt-3 text-2xl font-bold tracking-[-0.04em] sm:text-[28px]", children: song.title || song.filename }), _jsx("p", { className: "mt-1 text-sm text-[#788091]", children: song.artist || '—' })] }), _jsx("button", { className: "rounded-full p-2.5 transition hover:bg-[#f7f7fa] text-[#9ba1ae]", "aria-label": "Toggle favorite", children: _jsx(Icon, { name: "heart", size: 21 }) })] }), _jsxs("div", { className: "mt-6", children: [_jsx("button", { className: "group relative block h-2 w-full overflow-hidden rounded-full bg-[#eceef2]", onClick: (e) => {
                                        const rect = e.currentTarget.getBoundingClientRect();
                                        const newPos = ((e.clientX - rect.left) / rect.width) * (status.duration || 0);
                                        onSeek(newPos);
                                    }, "aria-label": "Seek through song", children: _jsx("span", { className: "absolute inset-y-0 left-0 rounded-full bg-[#6458e8]", style: { width: `${progress}%` } }) }), _jsxs("div", { className: "mt-2 flex justify-between text-[11px] font-medium tabular-nums text-[#8b92a1]", children: [_jsx("span", { children: formatTime(status.elapsed) }), _jsxs("span", { children: ["-", formatTime(Math.max(0, (status.duration || 0) - status.elapsed))] })] })] }), _jsxs("div", { className: "mt-4 flex items-center justify-between", children: [_jsxs("div", { className: "flex w-[84px] items-center gap-2 text-[#858c9b]", children: [_jsx(Icon, { name: "volume", size: 18 }), _jsx("input", { type: "range", min: "0", max: "100", value: volume, onChange: (e) => setVolume(Number(e.target.value)), className: "w-full", "aria-label": "Volume" })] }), _jsxs("div", { className: "flex items-center gap-4 sm:gap-6", children: [_jsx("button", { onClick: () => onSkip(-1), className: "text-[#51596a] transition hover:text-[#6458e8]", "aria-label": "Previous", children: _jsx(Icon, { name: "back", size: 21 }) }), _jsx("button", { onClick: status.playing ? onPause : onPlay, className: "flex h-[54px] w-[54px] items-center justify-center rounded-full bg-[#6458e8] text-white shadow-[0_8px_20px_rgba(100,88,232,0.28)] transition hover:bg-[#574bd8]", "aria-label": status.playing ? 'Pause' : 'Play', children: _jsx(Icon, { name: status.playing ? 'pause' : 'play', size: 23, filled: !status.playing }) }), _jsx("button", { onClick: () => onSkip(1), className: "text-[#51596a] transition hover:text-[#6458e8]", "aria-label": "Next", children: _jsx(Icon, { name: "forward", size: 21 }) })] }), _jsx("div", { className: "flex w-[84px] justify-end", children: _jsx("span", { className: "rounded-md bg-[#f3f2fb] px-2 py-1 text-[10px] font-bold text-[#6559d9]", children: "LED GUIDE" }) })] })] })] }) }));
}
