import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Icon from './Icon';
import { tempoMarking } from '../utils/format';
export default function TempoCard({ status, onTempoChange }) {
    if (!status)
        return null;
    const tempo = status.effective_bpm;
    const marking = tempoMarking(tempo);
    return (_jsxs("div", { className: "relative rounded-[20px] border border-[#e5e7ec] bg-white p-5 shadow-[0_8px_28px_rgba(23,32,51,0.03)] sm:p-6 lg:col-span-1 lg:row-start-1", children: [_jsxs("div", { className: "flex items-center gap-2.5", children: [_jsx("span", { className: "text-[#6458e8]", children: _jsx(Icon, { name: "metronome", size: 20 }) }), _jsx("h2", { className: "font-bold", children: "Tempo" })] }), _jsxs("div", { className: "mt-6 flex items-center", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("div", { children: [_jsx("span", { className: "text-[40px] font-bold leading-none tracking-[-0.06em]", children: tempo }), _jsx("span", { className: "ml-2 text-xs font-bold uppercase text-[#959ba7]", children: "BPM" })] }), _jsxs("div", { className: "flex flex-col gap-1", children: [_jsx("button", { onClick: () => onTempoChange(Math.min(180, tempo + 1)), className: "flex h-7 w-8 items-center justify-center rounded-md border border-[#e2e4e9] bg-[#fafbfc] text-base font-semibold leading-none text-[#626a7a] transition hover:border-[#aaa3ef] hover:bg-[#f2f0ff] hover:text-[#6458e8]", "aria-label": "Increase tempo", children: "+" }), _jsx("button", { onClick: () => onTempoChange(Math.max(40, tempo - 1)), className: "flex h-7 w-8 items-center justify-center rounded-md border border-[#e2e4e9] bg-[#fafbfc] text-base font-semibold leading-none text-[#626a7a] transition hover:border-[#aaa3ef] hover:bg-[#f2f0ff] hover:text-[#6458e8]", "aria-label": "Decrease tempo", children: "\u2212" })] })] }), _jsx("span", { className: "absolute right-5 top-5 rounded-full bg-[#edf8f3] px-2.5 py-1 text-[10px] font-bold text-[#42966f] sm:right-6 sm:top-6", children: marking })] }), _jsxs("p", { className: "mt-5 text-[10px] font-medium text-[#9298a5]", children: ["Original tempo: ", status.bpm, " BPM"] })] }));
}
